finos/OpenMAMA

common/c_cpp/src/c/darwin/port.h
common/c_cpp/src/c/linux/port.h
common/c_cpp/src/c/windows/wombat/port.h
mama/c_cpp/src/c/dqstrategy.c
mama/c_cpp/src/c/listenermsgcallback.c
mama/c_cpp/src/c/mama.c
mama/c_cpp/src/c/mama/publisher.h
mama/c_cpp/src/c/playback/playbackcapture.c
mama/c_cpp/src/c/publisher.c
mama/c_cpp/src/c/publisherimpl.h
mama/c_cpp/src/c/statslogger.c
mama/c_cpp/src/c/transport.c
mama/c_cpp/src/cpp/MamaDictionary.cpp
mama/c_cpp/src/cpp/MamaMsgQual.cpp
mama/c_cpp/src/cpp/MamaPublisher.cpp
mama/c_cpp/src/cpp/MamaSource.cpp
mama/c_cpp/src/cpp/MamaTransport.cpp
mama/c_cpp/src/cpp/mama/MamaPublisher.h
mama/c_cpp/src/examples/c/mamalistencachedc.c
mama/c_cpp/src/examples/cpp/mamalistencachedcpp.cpp
mama/c_cpp/src/testtools/performance/c/mamaconsumerc_v2.c
mama/c_cpp/src/testtools/performance/c/mamaproducerc_v2.c
mama/dotnet/src/cs/MamaPublisher.cs
mama/dotnet/src/cs/MamaTransport.cs
mama/jni/src/c/mamapublisherjni.c
mama/jni/src/com/wombat/mama/MamaPublisher.java
mama/jni/src/com/wombat/mama/MamaTransport.java

this is a compilation of patches outstanding from the old email patch submission process.
they have been tested against qpid 0.9.1 and pass all unit tests:
```bash
[ RUN      ] MsgF64Tests.updateF64InValid
[       OK ] MsgF64Tests.updateF64InValid (2 ms)
[ RUN      ] MsgF64Tests.getF64Valid
[       OK ] MsgF64Tests.getF64Valid (4 ms)
[ RUN      ] MsgF64Tests.getF64InValid
[       OK ] MsgF64Tests.getF64InValid (3 ms)
[ RUN      ] MsgF64Tests.getF64InValidF64
[       OK ] MsgF64Tests.getF64InValidF64 (3 ms)
[----------] 7 tests from MsgF64Tests (22 ms total)
[----------] Global test environment tear-down
[==========] 456 tests from 72 test cases ran. (3730 ms total)
[  PASSED  ] 456 tests.
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …

outstanding patches

---

mama/c_cpp/src/c/mama.c

Please see linked issue #95 for further info. 
Thanks,
Adrienne
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/96)

Additional tidyup around error code handling.

---

mama/c_cpp/src/c/listenermsgcallback.c
mama/c_cpp/src/c/mama.c
mama/c_cpp/src/c/subscription.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/131)

Fixed mixed declarations which popped up recently

---

mama/c_cpp/src/c/mama.c

We have a payload which on _init() creates a mama transport to pull down configuration files. This has been broken currently as the transport_create() is failing due to not having loaded entitlements bridges yet.
As mentioned, our payload calls mamaTransport_create(). This fails because mama_open() tries to load the payload *before* the entitlements bridge. After the recent changes to entitlements in 6.0.7 all transports need to have an entitlements bridge associated with them, so if it hasn't been loaded yet transport_create() will fail.
Checked unit tests as well as pub/sub, previous behaviour unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

PLAT-620: Payload unable to initialise when creating a transport

---

mama/jni/src/com/wombat/mama/MamaMsgStatus.java

STATUS_DELETE mapping added inside stringForStatus(). It was missing.
STATUS_DELETE mapping added inside stringForStatus(). It was missing.
Try to add in your cmd arg -msgstatus 17, which is the value for STATUS_DELETE.. You can easily print this string using MamaMsgStatus.stringForStatus(msg) in your program.

[PLAT-589] - Mapping STATUS_DELETE in com.wombat.mamda.MamdaMsgStatus.stringForStatus().

---

mama/c_cpp/src/testtools/performance/c/mamaproducerc_v2.c

This option allows users to specify a number of times to rewind a
playback file, or use -1 for infinite rewinds. Without this change,
mamaproducerc_v2 would always exit when a playback had completed
its first run through.
Also added the other playback parameters to the help text to shed
some light on how to use the replay functionality.
Note that unlike capturereplay, this tool does not support initial
and recap responses as it does not use the DQ Publisher.

EXAMPLE: Added -rewind option to mamaproducerc_v2

---

.travis.yml
release_scripts/ci-run.py
site_scons/community/linux.py

This will allow us to use travis for a rough CI which will soon show if
contributors are introducing unit test failures during their submissions.

Added initial travis script for OpenMAMA

---

release_scripts/openmama-rpm.sh

Problem was simply fedora 22 being EOL and mock configs no longer
being available. Took corrective action:
- Made mock builds be based on configs on system rather than hard
coded values
- Tidied up logging for rpm script
*This should be a brief one line description of the pull request*
*This is where you can describe your proposed change in more detail.*
*This is where you should describe how you have tested your changes.
It is expected at a minimum that this will not break break the build and that all
unit tests complete successfully. If you are fixing a certain behavior, you
should include some example output.*

BUILD: Fix for RPM build failure

---

SConstruct
site_scons/community/command_line.py

It never worked from the looks of it anyway, so removing.

Removed package option from linux builds

---

mama/jni/src/com/wombat/mama/MamaPublisherCallback.java
mama/jni/src/com/wombat/mama/examples/MamaPublisherJava.java

Fixed issue with missing onSuccess declaration

---

.clang-format
mama/c_cpp/src/testtools/capturereplay/c/capturereplayc.c

Bunch of general cleanups to `capturereplay`, including reformatting the main source file, addition of comments explaining behaviour, and the addition of a symbol list file. 
Changes are divided into three commits: 
* Reformatting source file.
* Addition of comments and additional status checks.
* Addition of symbol file option.
Builds completed at each stage. Capture replay functionality compared before and after, no differences noticed.

'capturereplayc' enhancements

---

mama/c_cpp/src/c/reservedfields.c

Small tidyup of the reservedfields.c file
Signed-off-by: Gary Molloy <gmolloy@velatt.com>
n/a
n/a

PLAT-1189: Reserve fields tidyup

---

mama/c_cpp/src/cpp/MamaMsgField.cpp
mama/c_cpp/src/cpp/mama/MamaMsgField.h

Details in mailing list thread:
https://lists.openmama.org/pipermail/openmama-dev/2017/002107.html

Fixed memory leak in MamaMsgField

---

common/c_cpp/src/c/windows/wombat/port.h
mama/c_cpp/src/c/mama/msg.h
mama/c_cpp/src/c/msg.c
mama/c_cpp/src/gunittest/c/mamamsg/msggeneraltests.cpp

These changes add mamaMsg_toNormalizedString and mamaMsg_toJsonString.

Added MAMA Msg toString Functions

---

mama/c_cpp/src/gunittest/c/mamadatetime/datetimetest.cpp
mama/c_cpp/src/gunittest/cpp/MamaDateTimeTest.cpp

Fixed recently introduced compiler warnings

---

mama/c_cpp/src/c/msg.c
mama/c_cpp/src/c/payloadbridge.h
mama/c_cpp/src/c/registerfunctions.c

added desrialize, check in msg.c

PLAT-980: added desrialize, check in msg.c (#121)

---

mama/jni/build.gradle
mama/jni/gradle.properties
mama/jni/src/CMakeLists.txt
mama/jni/src/main/java/com/wombat/mama/MamaDateTime.java
mama/jni/src/main/java/com/wombat/mama/MamaError.java
mama/jni/src/main/java/com/wombat/mama/MamaMsg.java
mama/jni/src/main/java/com/wombat/mama/MamaPrice.java
mama/jni/src/main/java/com/wombat/mama/MamaPricePrecision.java
mama/jni/src/main/java/com/wombat/mama/examples/MamaListen.java
mamda/java/CMakeLists.txt
mamda/java/build.gradle
mamda/java/gradle.properties
mamda/java/src/main/java/com/wombat/mamda/MamdaAuctionListener.java
mamda/java/src/main/java/com/wombat/mamda/MamdaConcreteBasicEvent.java
mamda/java/src/main/java/com/wombat/mamda/MamdaFields.java
mamda/java/src/main/java/com/wombat/mamda/MamdaOrderImbalanceListener.java
mamda/java/src/main/java/com/wombat/mamda/MamdaQuoteUpdate.java
mamda/java/src/main/java/com/wombat/mamda/MamdaSecurityStatus.java
mamda/java/src/main/java/com/wombat/mamda/MamdaSecurityStatusUpdate.java
mamda/java/src/main/java/com/wombat/mamda/MamdaTradeCancelOrError.java
mamda/java/src/main/java/com/wombat/mamda/MamdaTradeCorrection.java
mamda/java/src/main/java/com/wombat/mamda/MamdaTradeListener.java
mamda/java/src/main/java/com/wombat/mamda/MamdaTradeRecap.java
mamda/java/src/main/java/com/wombat/mamda/MamdaTradeReport.java
mamda/java/src/main/java/com/wombat/mamda/examples/MamdaBookTicker.java
mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBook.java
mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookEntry.java
mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookPriceLevel.java

Added gradle configuration to make it possible to upload to maven
central. It also fixed javadoc errors which were required.

Added maven central tasks and fixed javadoc error

---

mama/c_cpp/src/examples/c/mamalistenc.c

New feature added to mamalistenc to redirect output to a file.  Also added a signal handler so that we can execute a proper shutdown on exit.  There has also been some minor tidy-ups etc...

Enhancement mamalistenc

---

mama/c_cpp/src/c/payload/qpidmsg/qpidcommon.c
mama/c_cpp/src/c/payload/qpidmsg/qpidcommon.h

resolve build errors w/"static inline" - #402

---

cmake/FindAPR.cmake
common/c_cpp/src/c/MRSWLock.c
common/c_cpp/src/c/darwin/wombat/port.h
common/c_cpp/src/c/darwin/wombat/wUuid.h
mama/c_cpp/src/c/CMakeLists.txt

- first cut at building on Mac
*This is where you can describe your proposed change in more detail.*
Tested w/Xcode Version 11.3.1

first cut at building on Mac

---

mama/c_cpp/src/c/msg.c

calling mamaMsgImpl_setBridgeImpl unnecessarily leaks

---

common/c_cpp/src/c/property.c

improved debug msg

---

ansible/demo-provision.yml
devops/vagrant/Vagrantfile

Added third party repo for demo and switched to next branch

---

release_scripts/build-package.sh
tutorials/c/01-quickstart/CMakeLists.txt
tutorials/cpp/01-quickstart/CMakeLists.txt
tutorials/csharp/01-quickstart/01-quickstart.csproj

Also added license and license information to FPM package.

Added OPENMAMA_ROOT env variable parsing for quickstart

---

README.md

Updating `README.md` with FINOS `Active` badge, replacing the old `Incubating` one

Setting FINOS active badge

---

devops/build/ci-run.macos.sh

Fixed issue with OSX skipping unit testing

---

ansible/demo-provision.yml
devops/vagrant/Dockerfile.vagrant
devops/vagrant/Vagrantfile
devops/vagrant/entrypoint.sh
devops/vagrant/openmama-capturereplayd.sh

These are some fixes to allow us to run the vagrant demo environment as a docker image.

OpenMAMA demo docker fixes

---

mama/dotnet/src/nunittest/MamaCommon.cs
mama/dotnet/src/nunittest/MamaEnableLoggingTest.cs
mama/dotnet/src/nunittest/MamaEnqueueEventTest.cs
mama/dotnet/src/nunittest/MamaGetLogLevelTest.cs
mama/dotnet/src/nunittest/MamaLogTest.cs
mama/dotnet/src/nunittest/MamaLogToFileTest.cs
mama/dotnet/src/nunittest/MamaMsgVectorMsgTest.cs
mama/dotnet/src/nunittest/MamaMsgVectorPriceTest.cs
mama/dotnet/src/nunittest/MamaMsgVectorStringTest.cs
mama/dotnet/src/nunittest/MamaSetLogFilePolicyTest.cs
mama/dotnet/src/nunittest/MamaSetLogLevelTest.cs
mama/dotnet/src/nunittest/MamaSetLogSizeTest.cs
mamda/dotnet/src/examples/MamdaExamplesCommon/ComboTicker.cs
mamda/dotnet/src/examples/MamdaExamplesCommon/UnderlyingTicker.cs

Updated C# Unit Tests themselves to Nunit 3.x

---

mama/dotnet/src/cs/MAMA.cs
mama/dotnet/src/cs/MamaQueue.cs

Added Mama.GetLogLevelForString and MamaQueue.setQueueName for C#

---

mama/c_cpp/src/c/subscription.c

Fixed memory leak in image request during subscription cleanup

---

mama/jni/src/c/mamasubscriptionjni.c

Fixed crashing issue on setup fail for mamajni

---

.github/workflows/main.yml

Added Visual Studio 2022 to GH Actions

---

mama/c_cpp/src/c/bridge/base/basedefs.h
mama/c_cpp/src/c/bridge/base/bridge.c
mama/c_cpp/src/c/bridge/base/io.c
mama/c_cpp/src/c/mama/integration/bridge/base.h

Updated base bridge to isolate IO implementation

---

mama/c_cpp/src/c/bridge/base/timer.c

Added locking around base bridge timer synchronization

---

mama/c_cpp/src/c/endpointpool.c

Fixed crashing issue with endpoint destruction and callback

---

.gitattributes

Removed gitattributes file

---

devops/build/ci-run.sh

Added cloudsmith api check before attempted upload

---

CMakeLists.txt

Added mandatory OPENMAMA_VERSION if non git build

---

mama/c_cpp/src/c/mama.c
mama/c_cpp/src/c/mama/mama.h
mama/c_cpp/src/c/resourcepool.c
mama/c_cpp/src/cpp/mama/mamacpp.h
mama/c_cpp/src/cpp/mamacpp.cpp
mama/dotnet/src/cs/MAMA.cs
mama/dotnet/src/cs/MamaResourcePool.cs
mama/jni/src/c/mamajni.c
mama/jni/src/main/java/com/wombat/mama/Mama.java
mama/jni/src/main/java/com/wombat/mama/MamaResourcePool.java

Added in Mama.loadDefaultProperties and added init to resource pool

---

mama/c_cpp/src/c/mama.c

Modified mama_loadDefaultProperties not to override existing configuration
