finos/OpenMAMA

common/c_cpp/src/c/SConscript.win, common/c_cpp/src/c/commonc.vcproj, common/c_cpp/src/c/memnode.c, common/c_cpp/src/c/mempool.c, common/c_cpp/src/c/wombat/memdefs.h, common/c_cpp/src/c/wombat/memnode.h, common/c_cpp/src/c/wombat/mempool.h
This moves some code which was used in the qpid proton bridge for memory pool management into the common library as well as the allocateBufferMemory utility function. Once the qpid broker functionality is merged, the relevant changes for qpid to use the new common functions will be merged in too.
=> Adding mempool and memnode for managing elastic buffers

mama/c_cpp/src/c/bridge/qpid/transport.c
This bug was introduced recently when trimming out some shutdown
code which was deemed to no longer be required. However it did
put the application in a state where a ctrl+c was required to
interrupt the blocking receive loop. This change introduces a
timeout of 1ms (non-configurable at the moment) for each recv
call which allows the thread to avoid deadlock.
=> QPID: Fixed issue with qpid deadlock in timer unit tests

common/c_cpp/src/c/darwin/port.h, mama/c_cpp/src/c/bridge/qpid/transport.c, mama/c_cpp/src/c/payload/qpidmsg/field.c, mama/c_cpp/src/c/payload/qpidmsg/payload.c, site_scons/community/command_line.py
As per email chain, minor changes to allow compiling with clang
* QPID - Fix for missing method name in transport.c
* QPID - Fix for double const in Vector macro calls
* COMMON - Port update in Darwin for macros added in Yosemite for htonll
* SCONS - Added 10.11 build flag for Xcode 7 support
Pub / Sub working + Unit Tests passing on Mac OS X 10.10
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/24)
=> QPID and MAC Updates

common/c_cpp/src/c/SConscript, common/c_cpp/src/c/darwin/clock.c, common/c_cpp/src/c/darwin/port.h, mama/c_cpp/src/testtools/performance/c/mamaconsumerc_v2.c, mama/c_cpp/src/testtools/performance/c/mamaproducerc_v2.c
Replacing [bz-109](http://bugs.openmama.org/show_bug.cgi?id=109) and [bz-110](http://bugs.openmama.org/show_bug.cgi?id=110).
Comments the original tickets:
[bz-109](http://bugs.openmama.org/show_bug.cgi?id=109):
> Mac OS X does not support the clock_gettime function that is used in a number of the performance testing applications, but does have equivalient fucntions..
> This change wraps the time functions from the mac behind clock_gettime function
> Tested on
> * Mac OS X 10.9.2 x86_64
> * Ubuntu 12.04 x86_64
> With
> * Mamapublisherc / MamaSubscriberc
> * Mamainboxc
> * Mamalistenc / Capturereplay
> * Mamaproducerc_v2 / Mamaconsumerc_v2
> * Unit Tests
[bz-110](http://bugs.openmama.org/show_bug.cgi?id=110)
> Added support for compiling and running on Mac OS X.
> Excludes support for …
=> [BZ-109/110] OSX compatibility fixes

site_scons/community/linux.py
Add scons target for Linux 32-bit build. Also add FLAGS for GNU compilers. Also add CC and CXX from environment to use an alternative version of the GNU compiler.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/93)
=> SCONS: add Linux target for 32-bit build

mama/c_cpp/src/c/subscription.c
The following failure can be seen across all languages: 'mamaSubscription_processMsg() failed. [6342112]'
I only affected the logging. Basically the workaround here is correcting the possible case where we are returning junk value inside mamaSubscription_processMsg().
It can be easily replicated using FH/PUB + SUB (i.e, mamalistencpp).
Signed-off-by: Marti Queralt <m.queralt@daxplat01v.srl.srtechlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/180)
=> [PLAT-540] - Correcting possible junk return value in mamaSubscription_processMsg

mama/c_cpp/src/c/entitlement/oea/oea.c
Core seen when using a misconfigures altuserid with OEA entitlements.
Root cause is seen to be memory management in oeaEntitlementBridge.
Checked with both basic and market data subscriptions using OEA entitlements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/178)
=> PLAT-537: segfault  in oea entitlement bridge

mamda/java/build.xml
MAMA already defaults to ant version 1.5 for JNI. This will bring MAMDA inline with it.
Build remains working on older ant 1.4 version as well as newer 1.5
Signed-off-by: Matt Mulhern <m.mulhern@srtechlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/166)
=> MAMDA: ANT: Bumping minimum enforced java version from 1.4 to 1.5

mama/c_cpp/src/c/subscription.c
mamaSubscription_create core dumps when a NULL symbol is used. Additional NULL check before string.h function calls is needed.
Check for NULL pointers in all calls to string.h functions in the subscription functions.
Use of a NULL symbol in a symbol list subscription
Signed-off-by: Marti Queralt <m.queralt@daxplat01v.srl.srtechlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/177)
=> [PLAT-383] - Additional NULL check before string.h function calls added.

mamda/dotnet/src/cs/MamdaSubscription.cs, mamda/java/com/wombat/mamda/MamdaSubscription.java
Calling MamdaSubscription.deactivate() in C# was resulting in an error / unhandled exception.
Calling MamdaSubscription.deactivate() in C# was not working properly resulting in the following issue:
Could not deallocate mamaSubscription as it has not been destroyed.
Wombat.MamaException: mamaStatus: (MAMA_STATUS_SUBSCRIPTION_INVALID_STATE)
JAVA was also updated to reflect this change (however the same issue didn't not exist in JAVA)
For testing I simply modified the MamdaListen C# example application and added the following into the onMsg() callback:
```c#
Console.WriteLine("Mamda subscription deactivate called.");
try
{
subscription.deactivate();
}
catch (Exception)
{
Console.WriteLine("Could not deactivate subscription");
}
```
C# Output, subscribing to the symbol "SPY" (Before)
``` …
```
=> PLAT-100: Mamda subscription deactivation failure

mama/c_cpp/src/c/subscription.c
Reverts OpenMAMA/OpenMAMA#177
Mixed declaration is introduced on windows with this change which causes build failure:
http://ci.openmama.org:8080/job/OpenMAMA_Next_Branch_VS_2012/55/console
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/184)
=> Revert "[PLAT-383] - Additional NULL check before string.h function calls added."

mama/jni/src/com/wombat/mama/MamaStatus.java, mamda/java/com/wombat/mamda/MamdaErrorCode.java, mamda/java/com/wombat/mamda/MamdaSubscription.java
MamdaSubscription was found to be incorrectly mapping a MamaStatus to a MamdaErrorCode.
This patch adds a new helper function `MamdaErrorCode.codeForMamaStatus` to fix this error.
Also added a few relevant MamaStatus'es which were missing from JNI.
1) publish a message with status NOT_PERMISSIONED:
```./mamapublisherc -tport pub -msgstatus 12 -msgtype 21 -s CTA.SPY -l _MD.CTA -i 3```
2) subscribe to it:
```
java MamdaListen -tport sub -S CTA -s SPY -v -v -v -v
```
you'll get the following **without the fix**:
```
Error (SPY)Severity: 2 errorCode: -1 errorStr: UNKNOWN
```
With the fid, this will properly map to a NOT_PERMISSIONED error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> MamdaSubscription incorrectly mapping MamaStatus to MamdaErrorCode

mama/c_cpp/src/c/mama/msg.h, mama/c_cpp/src/c/msg.c, mama/c_cpp/src/c/payload/qpidmsg/field.c, mama/c_cpp/src/c/payload/qpidmsg/payload.c, mama/c_cpp/src/c/payload/qpidmsg/qpidcommon.h, mama/c_cpp/src/c/payload/qpidmsg/qpidpayloadfunctions.h, mama/c_cpp/src/c/payloadbridge.h, mama/c_cpp/src/c/registerfunctions.c, mama/c_cpp/src/gunittest/c/mamamsg/msgvectortests.cpp, mama/c_cpp/src/gunittest/c/payload/fieldvectortests.cpp, mama/c_cpp/src/gunittest/c/payload/payloadvectortests.cpp
QPIDMSG: Added implementation for the vector price / time functions
This patch adds support for vector price / date time to the qpid payload
bridge. It's worth noting that the function prototypes have also been
updated to reflect the way in which these functions are actually
expected to behave. This makes the code easier to understand for third
party payload bridge developers, but has the unfortunate side effect
of producing warnings while compiling until the MAMA Msg interface
is updated to reflect the same function sets.
All unit test pass which cover this functionality pretty well now, and I also compiled the omnm payload against this version to verify that it worked ok without introducing any problems.
---
This change is [<img …
=> Feature mamamsg vector price datetime

common/c_cpp/src/c/property.c, common/c_cpp/src/c/property.h
Added support for format strings when evaluating properties
Added a new method properties_GetPropertyValueUsingFormatString to allow the
caller to provide a sprintf style format string inline and provide a default
to reduce the amount of code required when performing common property parsing
tasks.
Also simplified properties_GetPropertyValueAsBoolean to use strtobool instead
of duplicating the strings to check for boolean evaluation.
I have just added some OpenMAMA ZeroMQ code which makes use of this functionality. Note this is the same code that formerly lived in the qpid bridge so once this gets into next, some qpid changes to make use of it will follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" …
=> COMMON: Added support for format strings when evaluating properties

mama/c_cpp/src/cpp/MamaQueue.cpp, mama/c_cpp/src/cpp/mama/mamacpp.h, mama/c_cpp/src/cpp/mamacpp.cpp
Currently, it is the responsibility of the middleware bridge to clean up it's default queue. In CPP, `Mama::getDefaultEventQueue` returns a CPP wrapper to this c-level queue. 
The wrapper is not tidied up and manually deleting could lead to a double free (mamaQueue::destroy tells the mw bridge to clean up the queue, which may be done again on bridge_close).
This patch keeps a track of any CPP wrappers made to default queues and cleans them up in Mama::close. This way the developer does not have to keep track of the default Queue wrapper created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmama/openmama/174)
=> PLAT-493: Keeping track of CPP wrappers to default queue

mama/c_cpp/src/c/subscription.c
Wildcard subscription OnMsg callback is called with NULL instead of topic string
The message callback behaviour for a wildcard subscription has changed. The callback definition includes a topic string argument, for example:
<quote>
void MAMACALLTYPE
subscriptionOnMsg  (mamaSubscription subscription,
mamaMsg msg,
const char*         topic,             // <-------- here
void *closure,
void *itemClosure)
</quote>
With the OpenMAMA 2.3.3, this argument actually received the topic string of the received message. 
With the OpenMAMA 2.4.1, the topic argument is null.
For example, running the modified OpenMAMA 2.3.3 sample mamalistenc that listens on a wildcard topic and on receipt of a message, prints out the received topic, the modified …
=> Wildcard subscription OnMsg callback is called with NULL instead of topic

mama/c_cpp/src/c/dqstrategy.c, mama/c_cpp/src/c/mama/subscription.h, mama/c_cpp/src/c/subscription.c, mama/c_cpp/src/c/subscriptionimpl.h, mama/c_cpp/src/cpp/MamaSubscription.cpp, mama/c_cpp/src/cpp/mama/MamaSubscription.h, mamda/c_cpp/src/cpp/MamdaSubscription.cpp, mamda/c_cpp/src/cpp/mamda/MamdaSubscription.h
Adding the ability to use a separate timeout for subscription recaps from the initial request.
Added the following implementations for mama/mamda:
```
mamaSubscription_setRecapTimeout()
mamaSubscription_getRecapTimeout()
MamaSubscription::setRecapTimeout()
MamaSubscription::getRecapTimeout()
MamdaSubscription::setRecapTimeout()
MamdaSubscription::getRecapTimeout()
```
This new timeout is entirely optional. On the first call of `mamaSubscription_getRecapTimeout`, if the recap timeout has not been expliticaly been set it well be set at that time *to the value set currently for the initial timeout*. This way, existing code that just calls `mamaSubscription_setTimeout()` will behave in the same manner as before.
Tested by simulating dropped …
=> PLAT-438: Implementing a seperate timeout for subscription recaps.

mama/c_cpp/SConscript.win, mama/c_cpp/src/c/entitlement/SConscript, mama/c_cpp/src/c/entitlement/noop/SConscript
Updated scons script to build noop on windows
Fix applied as per issue #192. Scons builds won't include the noop
entitlement bridge without this change.
Build was tested on both linux and windows.
=> SCONS: Updated scons script to build noop on windows

common/c_cpp/SConscript.win, common/c_cpp/src/gunittest/SConscript, common/c_cpp/src/gunittest/c/SConscript, mama/c_cpp/SConscript.win, mama/c_cpp/src/c/bridge/qpid/SConscript, mama/c_cpp/src/c/bridge/qpid/SConscript.win, mama/c_cpp/src/c/fieldcache/fieldcachefieldimpl.h, mama/c_cpp/src/c/fieldcache/fieldcachelist.h, mama/c_cpp/src/c/fieldcache/fieldcachemap.h, mama/c_cpp/src/c/fieldcache/fieldcachemaparray.h, mama/c_cpp/src/c/fieldcache/fieldcachevector.h, mama/c_cpp/src/c/mamainternal.h, mama/c_cpp/src/c/msgutils.h, mama/c_cpp/src/c/payload/qpidmsg/SConscript.win, mama/c_cpp/src/examples/c/SConscript.win, mama/c_cpp/src/examples/cpp/SConscript.win, mama/c_cpp/src/gunittest/SConscript, mama/c_cpp/src/gunittest/c/MainUnitTestC.h, mama/c_cpp/src/gunittest/c/SConscript, mama/c_cpp/src/gunittest/c/mamamsg/msgvectortests.cpp, mama/c_cpp/src/gunittest/c/payload/payloadvectortests.cpp, mama/c_cpp/src/gunittest/cpp/SConscript, mama/dotnet/SConscript.win, mama/jni/SConscript.win, mamda/c_cpp/SConscript.win, mamda/dotnet/SConscript.win, mamda/java/SConscript.win, site_scons/community/command_line.py, site_scons/community/windows.py
Fix for #15
This fixes an issue where it was impossible to build multiple build types
using one command on windows. It also brings unit tests to the scons
windows builds.
Note that qpid_home on windows also points to the base proton directory
now rather than requiring the user to know to point to the 'proton-c'
subdirectory.
When building types beyond dynamic, this also flagged an issue where
several functions were not exported for DLL properly, particularly in
mamaFieldCache so this patch also resolves that issue by introducing the
correct function declarations.
=> SCONS: Fixed build issue with multiple build types on windows

release_scripts/ci-run.py
Fix for #194
Added initial version of CI script to allow CI builds to be run offline.
Note that it depends on the caller having a standard directory structure
set up for dependencies which is obviously OK for a CI environment where
this will always be consistent, but the directory structure itself will
need to be documented and advertised as well.
=> CI: Added new script to use for CI builds

mama/c_cpp/src/c/dqpublishermanager.c, mama/c_cpp/src/c/mama/dqpublishermanager.h, mama/c_cpp/src/cpp/MamaDQPublisherManager.cpp, mama/c_cpp/src/cpp/mama/MamaDQPublisherManager.h, mama/jni/src/com/wombat/mama/MamaDQPublisherManager.java
Method 'getPublisher' that is in Enterprise Mama for MamaDqPublisher is not in OpenMAMA. C/C++ and Java implementation of that method.
See committed code. It is very simple and basic implementation for getPublisher. Based on its C function, the C++ version basically calls the underlying C function and returns mamaDQPublisher's closure. In terms of Java's implementation, it uses the already created myTopics mapped variable to do all the required logic of getPublisher.
Check that MamaDqPublisherManager class provides a method to access the MamaDqPublisher and cache. Check that the C/C++-API provides a function to get a mamaDqPublisher. Check that values match those provided when the MamaDQPublisher was created. No OS or transport …
=> [PLAT-421] - New C, C++ and JAVA getPublisher implementation.

common/c_cpp/src/c/linux/wInterlocked.h
Decided to go with Daniel's patch in http://anonscm.debian.org/gitweb/?p=collab-maint/openmama.git;a=blob;f=debian/patches/0010-Support-atomic-operations-on-additional-CPUs.patch;hb=HEAD
It's nice because it leaves functionality as-is for x86, and only resorts to builtin atomics if it needs to.
Signed-off-by: Daniel Pocock <daniel@pocock.com.au>
=> COMMON: Support atomic operations on additional CPUs

mama/c_cpp/src/c/bridge.h, mama/c_cpp/src/c/bridge/qpid/publisher.c, mama/c_cpp/src/c/bridge/qpid/qpidbridgefunctions.h
Updated the prototype for the bridge function to be a mamaMsg
rather than a mamaMsg cast as a void* only to be cast back to
a mamaMsg in the bridge function itself.
=> Corrected prototype for bridgeMamaPublisherSendReplyToInbox (#38)

mama/c_cpp/src/c/transport.c
This change adds the fix suggested in #18 for the listeners list
in MAMA's transport.c to protect against instances where a
partially created transport (i.e. a transport whose creation
failed part of the way through) could cause a crash during
mamaTransport_destroy.
=> MAMA: Fixed issue where destroying partial transport crashes

common/c_cpp/src/c/windows/port.c, common/c_cpp/src/c/windows/wombat/port.h
The Windows port of wthread_cond_wait passes a pointer to a
LPCRITICAL_SECTION to both the LeaveCriticalSection and
EnterCriticalSection functions. These should both be
LPCRITICAL_SECTIONs themselves.
=> COMMON: Windows type fix for Windows port of wthread_cond_wait

common/c_cpp/src/c/commonc.vcxproj, common/c_cpp/src/c/property.c, common/c_cpp/src/c/property.h, common/c_cpp/src/c/wombat/wtable.h, common/c_cpp/src/c/wtable.c, mama/c_cpp/src/c/mama.c
Without this change, there is no way to specify a non-default properties
file which will be honoured by parts of the MAMA loading process including
the bridge loading stage without reporting an error.
Added new function for counting the number of properties which have been
specified and for counting the number of elements in a wtable. This is to
enable effective checking of whether or not property loading has been
successful so it can report an error only when necessary.
It will now only report an error if:
- A specific properties file was requested
- Default properties are being loaded and no existing properties are loaded
To use custom properties, use mama_setPropertiesFromFile or mama_setProperty
before mama_loadBridge is called.
=> MAMA: Fixed ability to use custom properties file

mama/jni/src/c/mamatransportjni.c
Miss-cast to a pointer value of mamaConnection variable inside mamaTransportImpl_getConnectionObject is causing a crash.
mamaConnection cConnection variable modified to not be a pointer anymore.
platformInfo was cast to a mamaConnection, but it was actually a mamaConnection.
Also the CAST_POINTER_TO_JLONG dereferences the ptr, which is at the incorrect level.
Follow steps pointed out in #69 's description. It shouldn't crash anymore.
=> [PLAT-398] - MAMA JNI crash in MamaListen.java when using platformInfo.toString().

mama/jni/src/c/mamajniutils.c
As per issue #181, without this change if using non-default MAMA
queues in JNI, application will hang on shutdown as it cannot
terminate the native threads.
Signed-off-as: Frank Quinn <fquinn.ni@gmail.com>
=> MAMAJNI: Updated JNI thread to use AttachThreadAsDaemon

mama/c_cpp/src/c/entitlement/oea/oea.c, mama/c_cpp/src/c/entitlement/oea/oea.h
Three new OEA properties added to MAMA
The following properties have been added to MAMA that will allow you to set OEA socket related tcp timeouts:
- mama.entitlement.oea.write_timeout
- mama.entitlement.oea.read_timeout
- mama.entitlement.oea.connection_timeout
These changes have been made in advance of OEA v3.8 so currently there is no way of testing this.
Signed-off-by: Gary Molloy <gmolloy@velatt.com>
=> PLAT-687: Make OEA Socket Timeouts Configurable in MAMA

mama/c_cpp/src/c/entitlement/noop/noop.c
Causes build error on visual studio versions prior to 2015.
=> MAMA: Removed mixed declaration in ent-noop

mama/c_cpp/src/c/entitlement/oea/oea.c
MAMA would core when running an entitled build but then fail to define any entitlement servers in the mama.properties.
Fixed the return code and error handling in the even that we fail to find any entitlement.servers in the mama.properties
With this change in place we now get the correct behaviour when no entitlement servers are defined:
```
$ mamalistenc -S UTP -tport tcp_sub -m wmw -s FR0000031122.EUR.XPAR
2016-08-31 14:45:51:
********************************************************************************
Warning: This is a developer release and has only undergone basic sanity checks.
It is for testing only and should not be used in a production environment
**********************************************************************************
2016-08-31 14:45:51: Failed to open properties …
```
=> PLAT-747: Mamalistenc cores on start up when entitlement servers are not defined

mama/c_cpp/src/c/subscription.c
A core was observed while running the example app "mamasubscriberc -w" within the function mamaSubscription_processWildCardMsg().  The issue is that currently we do not create an entitlement subscription for basic subscriptions.
Added additional entitlements check into mamaSubscription_processWildCardMsg() to check that we have an entitlement subscription before trying to verify if we are entitled to continue
With the patch applied we get the expected results from running "mamasubscriberc -w" and no core.
Signed-off-by: Gary Molloy <gmolloy@velatt.com>
=> PLAT-737: Core within mamaSubscription_processWildCardMsg()

mama/c_cpp/src/gunittest/c/payload/fieldvectortests.cpp, mama/c_cpp/src/gunittest/c/payload/payloadgeneraltests.cpp
Valgrind was complaining about uninitialized memory in unit tests.
This fixes these issues.
Signed-off-by: Frank Quinn fquinn.ni@gmail.com
=> Fixed valgrind reported issues with unit tests

mama/c_cpp/src/c/mama.c
Default value of mama.msg.allowmodify changed from "false" to "true".
mama.message.allowmodify controls whether or not MAMA is allowed to 
internally modify messages it has received.  Specifically it is checked inside 
mamaDqPublisher_send() when updating the sequence number and senderId 
of the outgoing message.  If mama.message.allowmodify is false, a copy of 
the message is taken at this point.  If it is true, the original message is 
updated.
In most cases it is in fact safe to modify the message.  The only case 
where it is not safe is when republishing messages from a Data Fabric 
Shared Memory transport.  Testing has discovered that copying the 
message adds around 2 microseconds to the time it takes to execute …
=> PLAT-839: Default value of mama.msg.allowmodify changed from "false" to "true"

OpenMama.sln, common/c_cpp/src/c/SConscript.win, common/c_cpp/src/c/commonc.vcxproj, common/c_cpp/src/c/fileutils.c, common/c_cpp/src/c/wombat/environment.h, common/c_cpp/src/c/wombat/fileutils.h, common/c_cpp/src/gunittest/c/SConscript, common/c_cpp/src/gunittest/c/UnitTestCommonC.vcxproj, common/c_cpp/src/gunittest/c/utiltest.cpp, mama/c_cpp/src/gunittest/c/dictionarytest.cpp
Added the fileUtils_findFileInPathList method for finding a file
within a delimited list of paths such as LD_LIBRARY_PATH or PATH,
and put it to work to fix an issue with the
MamaDictionaryTestC.LoadFromFileAndWriteToMsg unit test
=> COMMON: Added new method for finding a file in a PATH

mama/c_cpp/src/gunittest/cpp/MamaMsgTest.cpp
Fixed issue with MamaMsgTestCPP.TempCopyNotOwnerTest where the unit test
would fail because it assumed that the underlying payload was immutable.
With the recent changes submitted by Marti, this is no longer the default
case, so this test started to fail. This modification checks to see if any
bridges have marked the payloads as immutable before continuing with this
test.
=> UT: Fixed unit test for modifyable payloads

mama/c_cpp/src/examples/cpp/mamaiocpp.cpp, mama/dotnet/src/examples/MamaIo/MamaIoCS.cs
Windows *and* WMW only. Fixed bug where MAMA_STATUS_UNSUPPORTED_IO_TYPE was seeing whenever I/O type was not found.
New unknown I/O type handler implementation to fix the issue. Now, in case of 
failing this message will be logged: "Warning: Cannot create IO Handler for 
MAMA_IO_EXCEPT: not supported on current middleware".
Replication steps:
1. Start MamaIoCS.exe [Windows box]
`MamaIoCS.exe -m wmw -p 7777`
2. start netcat [linux box]
3. MamaIoCS.exe accepts a connection and produces error
`Accepting connection from 10.119.18.62:35485
Error creation IO Handler: Wombat.MamaException: mamaStatus: (MAMA_STATUS_UNSUPPORTED_IO_TYPE)
at Wombat.MamaWrapper.CheckResultCode(Int32 code)
at Wombat.MamaIo.create(MamaQueue queue, MamaIoCallback action, …
=> [PLAT-753] - Creation of the exceptionHandlers in a try/catch

common/c_cpp/src/c/strutils.c, common/c_cpp/src/gunittest/c/utiltest.cpp
The version parsing wasn't resilient to things like versions being
mid-string. These changes makes the function much more robust and
adds some argument validation and unit tests to cover this.
=> COMMON: Made version string parsing more robust

common/c_cpp/src/c/windows/wombat/port.h, mama/c_cpp/src/c/datetime.c, mama/c_cpp/src/c/datetimeimpl.h, mama/c_cpp/src/c/mama/datetime.h, mama/c_cpp/src/c/mama/msg.h, mama/c_cpp/src/c/mama/types.h, mama/c_cpp/src/c/msg.c, mama/c_cpp/src/cpp/datetime.cpp, mama/c_cpp/src/cpp/mama/MamaDateTime.h, mama/c_cpp/src/gunittest/c/mamadatetime/datetimetest.cpp, mama/c_cpp/src/gunittest/cpp/MamaDateTimeTest.cpp, mama/dotnet/src/cs/MamaMsg.cs, mama/jni/SConscript.win, mama/jni/src/c/mamadatetimejni.c, mama/jni/src/com/wombat/mama/MamaDateTime.java, mama/jni/src/junittests/MamaDateTimeSetTimeZone.java
This commit fixes existing issues in Extended MAMA Date Time.
I am taking this over as @garymolloy is out atm.
Added timespec based implementation for datetimei and updated C# and JNI
to use timespec. Code cleanup has been done too.
The timeval implementation works only for Linux based systems. Original
design documents assumed that the 'tv_sec' timeval on windows was a
time_t (as it is on linux), but it turns out that it is in fact a long
int, which is 4 bytes on windows for both 32 and 64 bit.
To provide a very similar alternative, this change introduces new
mamaDateTime methods which make use of timespec which is similar to
timeval, but uses time_t to store seconds and has nanosecond resolution.
This change also includes a definition of …
=> Mama date time new hacks

mama/c_cpp/src/c/mama.c, mama/c_cpp/src/c/mama/mama.h, mama/c_cpp/src/cpp/mama/mamacpp.h, mama/c_cpp/src/cpp/mamacpp.cpp, mama/c_cpp/src/gunittest/c/openclosetest.cpp, mama/c_cpp/src/gunittest/cpp/MainUnitTestCpp.cpp, mama/c_cpp/src/gunittest/cpp/MainUnitTestCpp.h, mama/c_cpp/src/gunittest/cpp/MamaOpenCloseTest.cpp
Exposing new accessors to find middleware and payload bridges which have already been loaded. 
Changes are relatively simple - adding new get*Bridge accessors to both C and C++, as well as exposing the loadPayloadBridge C++ method. 
New unit tests added to both C and C++ layers.
=> Expose Middleware and Payload Accessors

.clang-format
Add a .clang-format file which is a close approximation to the OpenMAMA
coding standard. Based on the LLVM core style, with additional changes.
Can be used by either the clang-format tool, vim plugins, or Visual
Studio code for formatting OpenMAMA src files.
=> [GENERAL] Add .clang-format to OpenMAMA root directory

common/c_cpp/src/c/thread.c, mama/c_cpp/src/c/bridge.h, mama/c_cpp/src/c/mama.c, mama/c_cpp/src/cpp/datetime.cpp, mama/c_cpp/src/gunittest/c/mamadatetime/datetimetest.cpp, mama/c_cpp/src/gunittest/c/payload/payloadgeneraltests.cpp, mama/c_cpp/src/gunittest/cpp/MamaDateTimeTest.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookWriter.cpp
- Fixed shutdown memory leak in wombatThread on shutdown
- Fixed several compiler warnings which had crept in recently
=> MAMA: Cleanup ahead of OpenMAMA 6.2.0 cut

mama/c_cpp/src/c/mama/publisher.h, mama/c_cpp/src/c/publisher.c, mama/c_cpp/src/cpp/MamaPublisher.cpp, mama/c_cpp/src/cpp/MamaPublisherImpl.h, mama/c_cpp/src/cpp/mama/MamaPublisherCallback.h, mama/c_cpp/src/examples/c/mamapublisherc.c, mama/c_cpp/src/examples/cpp/mamapublishercpp.cpp, mama/c_cpp/src/gunittest/c/publishertest.cpp, mama/c_cpp/src/gunittest/cpp/MamaPublisherTest.cpp, mama/dotnet/src/cs/MamaPublisher.cs, mama/dotnet/src/cs/MamaPublisherCallback.cs, mama/dotnet/src/examples/MamaPublisher/MamaPublisherCS.cs, mama/jni/src/c/mamapublisherjni.c, mamda/c_cpp/src/examples/mamdapublisher.cpp, mamda/c_cpp/src/examples/orderbooks/listenerBookPublisher.cpp, mamda/dotnet/src/examples/MamdaTradeTicker/MamdaTradeTicker.cs
Added support for onSuccess publisher events 
OpenMama clients using MamaPublisher in a Request/Response configuration can register MamaPublisherCallbacks to receive events from the bridge. This has been in place since 2.4.x. MamaPublisherCallbacks has a onError function but no onSuccess. A use-case for some OpenMama Request/Response clients is to expect asynchronous ack/nak events from the bridge. This PR adds onSuccess to enable the reporting of ack events to the client. 
C and C++ unit tests have been expanded to cover the onSuccess callback. These all pass on CentOS 7 except for MamaDictionaryTestC.LoadFromFileAndWriteToMsg which I couldn't get to pass even on the vanilla 'next' branch as dictionary1.txt seems to be missing from …
=> Added support for onSuccess publisher events

mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookListener.cpp, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBookListener.h
New feature would trigger callbacks for top of book price changes even when they would normally not be triggered due to happening inside a conflation interval. If a callback for a book update is triggered in this scenario, a new conflation interval will begin.
For testing purposes I hacked bookticker mamda app to enable conflation and my new feature.
=> [PLAT-888] - New feature: process during conflation timer when there's an update with changes on the top of the book.

mama/c_cpp/src/cpp/MamaMsg.cpp, mama/c_cpp/src/cpp/mama/MamaMsg.h, mama/c_cpp/src/gunittest/cpp/MamaMsgTest.cpp
- Add unit test to demonstrate memory leak in pre-existing OpenMAMA
codebase.
- Remove unnecessary C-layer mamaMsg tracking of vector messages in a
MamaMsg.  This fixes the memory leak.
Signed-off-by: Duane Pauls <duane.pauls@solace.com>
*Fix `mamaMsg` memory leak caused by tracking of `mamaMsg` objects parts of a `MamaMsg` vector within another `MamaMsg`.*
The way `mamaMsg` objects belonging to a `MamaMsg` vector within another `MamaMsg` is flawed.  I am unable to determine why this tracking is being done.  Removing the tracking solves the memory leak, and all unit tests pass.
The following scenarios were tested:
- The original scenario where the bug was discovered.  This scenario involved a modified `bookpublisher.cpp` publishing into a …
=> MAMACPP: Remove mCvectorMsg tracking in MamaMsg.

common/c_cpp/src/c/mempool.c, mama/c_cpp/src/c/bridge/qpid/transport.c
See issue #262. This was most likely introduced when memoryPool changes were
made, but there was an issue where a proton message was not initialized for
the temporary copies that are created when multiple subscribers are consuming
the same message. In addition there was another issue where the memory node
itself rather than its underlying buffer was being manipulated. This change
fixes both of the above.
Also fixed an issue with memoryPool_iterate which could cause all members
of the memory pool not to trigger a callback.
=> Fixed issue with multiple subscribers for same topic in qpid

mamda/java/com/wombat/mamda/MamdaSubscription.java
only creating an Exception if msgType is MamaMsgType.TYPE_DELETE
redundant object creation is fixed, fast-return in case subscription is null
final code is equivalent (minus redundant instance creation and fast exit), all invariants are preserved.
=> fixes #269: MamdaSubscription redundantly creates Exception instance in onMsg

mama/c_cpp/src/c/datetime.c, mama/c_cpp/src/c/datetimeimpl.h, mama/c_cpp/src/gunittest/c/mamadatetime/datetimetest.cpp
See issue #275. Only 32 bit linux effected.
The internal date type of MAMA Date Time was changes to ensure it is
explicitly 64 bit where time_t is not big enough. This is to allow
extended datetime methods to be used even on 32 bit linux machines
(it already worked fine on 32 bit windows machines). It still
prefers time_t though and when support for 32 bit linux is
eventually dropped, the explicit value will be removed in favour
of the more OS-native type.
This issue is concerned with large year values (i.e. beyond the year
2038). Processing dates before 1970 is unlikely to cause a problem
(since that time_t range starts at 1902).
There are still limitations on 32 bit linux though. In order to get /
set an extended date time, the F64 accessors will need to be used: …
=> Fixed issue with date time on 32 bit linux

mama/c_cpp/src/gunittest/c/publishertest.cpp
Signed-off-by: Chris Morgan <Christopher.Morgan@solacesystems.com>
On Win32 an SEH exception is thrown in the test body of MamaPublisherTestC.EventSendWithCallbacks when calling the onCreate callback of the publisher create function.  
From issue #271 : 
> I also, found one SEH exception in raise during one test, that gtest seemed to handle properly in the UnitTestMamaC on Win32, in publishertest.cpp.
The Test prints unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
It seems the publisher callback functions do not have the MAMACALLTYPE macro for __stdcall which seems to crash the test MamaPublisherTestC.EventSendWithCallbacks on Win32, surprisingly it does not crash in Win64.
The callbacks in …
=> Fix Win32 MamaPublisherTestC.EventSendWithCallbacks SEH exception.

mama/c_cpp/src/cpp/datetime.cpp, mama/c_cpp/src/cpp/mama/MamaDateTime.h
Simple C++ functions which immediately pass through to the equivalent C functions.
- [X ] MAMACPP
The new member functions setFromStructTimeSpec and getAsStructTimeSpec simply call the equivalent C functions. This change is per the RFC for Extended MAMA Date Time https://openmama.github.io/openmama_rfc_extended_datetime.html
Testing has been done using a client side OpenMAMA written in C++. This is such a simple change that as long as it compiles then the existing MamaDateTime C unit tests will suffice.
=> Extended the MamaDateTime C++ class with timespec get/set.

mama/c_cpp/src/gunittest/c/mamamsg/msgfieldcompositetests.cpp, mama/c_cpp/src/gunittest/c/publishertest.cpp
The test TEST_F (FieldPriceTestsC, updatePriceValid) Linux 32 bit cause heap corruption. The test uses the address of a mamaPrice instead mamaPrice casuing a sigabort on Linux 32 bit systems.
Both TEST_F (FieldPriceTestsC, getPriceValid), and TEST_F (FieldPriceTestsC, getPriceInValidField) use the address of a NULL mamaPrice instead of an initialize mamaPrice. This causes invalid writes during TEST_F (FieldPriceTestsC, getPriceValid) leading to heap corruption. 
When Running the Test without the fix a sigabort core happens. With the fix the test passes with a sigabort signal or core.
=> Linux 32 bit heap corruption in  TEST_F (FieldPriceTestsC, updatePriceValid)

mama/jni/src/junittests/MamaPublisherTest.java
The publisher unit test did not implement the onSuccess callback. This
change corrects this.
=> Fixed unit test not implementing publisher success

mama/c_cpp/src/c/datetime.c, mama/c_cpp/src/c/datetimeimpl.h, mama/c_cpp/src/c/mama/datetime.h, mama/c_cpp/src/cpp/datetime.cpp, mama/c_cpp/src/cpp/mama/MamaDateTime.h, mama/c_cpp/src/gunittest/c/mamadatetime/datetimetest.cpp, mama/c_cpp/src/gunittest/cpp/MamaDateTimeTest.cpp
The interface for getting and setting hints and precision was mixed up
with the non-extended methods for getting and setting the epoch time,
so this change introduces a few new methods for access to hints,
precision and epoch time with explicit 64 bit second types and
nanosecond resolution.
Relates to issues #285 and #286.
=> New extended epoch, hints and precision methods

mama/c_cpp/src/c/datetime.c
This is specifically for 32 bit linux which uses a 32-bit time_t,
therefore any timespec or timeval based accessors cannot sufficiently
represent a 64 bit value on such a platform.
This change will now advise the caller when an overflow would have
been caused by returning MAMA_STATUS_INVALID_ARG.
=> Getting out of range date value now returns error

LICENSE-3RD-PARTY.txt, README.md, SConstruct, mama/c_cpp/src/c/SConscript, mama/c_cpp/src/c/bridge/qpid/SConscript, release_scripts/openmama-rpm.sh, release_scripts/openmama.spec, site_scons/community/command_line.py
```
Updated licenses and installation files
Licensing is updated to include apache apr license details, and
configuration, readme and license files are now included in all builds
by default including RPMs and windows.
The libraries used during the build are also now included in the package
to avoid the user having to install any further dependencies. It also
ensures that versions match for compile vs run time and that we can
avoid the issue where qpid proton keeps changing its shared object name
(we may remove this from RPM builds when that volatility settles down).
Documentation in the README has also been updated to refer to the new
licensing file.
```
=> Feature licensing apr update

mama/c_cpp/src/c/datetime.c, mama/c_cpp/src/c/mama/datetime.h, mama/c_cpp/src/gunittest/c/mamadatetime/datetimetest.cpp
Windows string formatting crashed for years prior to 1601. Impacted
functions will now exit gracefully in this scenario with an error
code instead.
=> Fixed issue with crash for years prior to 1601

mama/c_cpp/src/c/mama/dqpublishermanager.h
The DQ Publisher Manager headers are mysterious beasts with no comments at all, and therefore very hard to understand. This PR addresses that by adding comments, thus making them only hard to understand instead. 
Add a bunch of comments. That should be all. 
Adding comments to a header file only, so shouldn't be any changes to functionality. Builds still complete successfully and unit tests run however, so no issues expected.
=> [MAMA] Add comments to the DQ Publisher Manager headers

mama/dotnet/src/cs/MamaMsgField.cs
Fixed crash in MamdaTradeTicker.cs
Fixed crash in MamdaTradeTicker, by adding in a member variable dateTime to MamaMsgField, which is initialised in the constructor and destroyed when MamaMsgField is destroyed. This is a reusable variable which is cleared and filled every time getDateTime() is called in MamaMsgField.cs.
Tested this change by running all of the ticker example applications. The MamdaTradeTickerCS no longer throws an error, and the other Ticker applications are unaffected.
=> Issue in dotnet with new mamaDateTime

mama/c_cpp/src/c/mama.c, mama/c_cpp/src/c/queue.c
When trying to optimise the deployment of MAMA based applications,
we want to make use of the thread affinity logic to bind to specific
cores. In order to do that, we need to know the names of the threads
being started by MAMA, but this is currently difficult (in particular if
you're working on an application with potentially large numbers of
threads).
This change adds standard logging to both locations where MAMA can start
new named threads - mama_startBackground, and mamaDispatcher_create. In
both cases, logging of the format:
<Method Name> (): Creating new background thread (name=<tread name>).
Has been added.
Signed-off By: Damian Maguire <dmaguire@velatt.com>
No functional changes have been made. Testing has been performed with
unit …
=> [MAMA] Add logging of thread names during creation

mama/c_cpp/src/c/mama.c
Some middlewares may attempt to load multiple payload bridges during
initialization, some of which may not always exist. This unfortunately
results in MAMA clients having to deal with spurious 'ERROR' logging and
may make them miss occasions when the logging actually indicates a
problem.
This changes adds support for configurable suppressing of this logging
using the following parameter:
mama.payload.suppress_load_failure_logging
Note: this has only been enabled for the specific case of missing
libraries for the payload. Other logging relating to payload loading
failures remains 'ERROR' level, as they represent a real issue which
should not be ignored.
Signed-off By: Damian Maguire <dmaguire@velatt.com>
Tested using the results of the
`MamaInternalTestC.loadPayloadBridgeInvalidName` test, …
=> [MAMA] Add ability to suppress logging of payload load failure.

mama/c_cpp/src/examples/mama.properties
Missing definition in mama.properties
The definition of mama.qpid.transport.pub.outgoing_url is missing from mama.properties.
Adding the property manually allows for running all examples.
=> [EXAMPLES] add missing property

mama/c_cpp/src/c/bridge/qpid/endpointpool.c
There is an off-by-one error in endpointPoolImpl_appendEachEndpoint which causes heap corruption.
When run under valgrind the offending code produces a memory error similar to the following, after which the program will terminate with a SEGV.
```
Invalid write of size 8
at 0x5F4E5A2: endpointPoolImpl_appendEachEndpoint (endpointpool.c:541)
by 0x56E8C87: wtable_for_each (wtable.c:64)
by 0x5F4E2E5: endpointPool_getRegistered (endpointpool.c:383)
by 0x5F4DB24: zmqBridgeMamaTransportImpl_dispatchThread (transport.c:1085)
by 0x3456E07A50: start_thread (pthread_create.c:301)
by 0x34566E89AC: clone (clone.S:115)
Address 0x5b61b20 is 0 bytes after a block of size 1,024 alloc'd
at 0x4A05EDF: calloc (vg_replace_malloc.c:710)
by 0x5F4DE2E: …
```
=> [MAMA] off-by-one error in endpointpool

mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookWriter.cpp
Signed-off-by: cjwmorgan-sol-sys <Christopher.Morgan@solacesystems.com>
Allows MamdaOrderBookWriter to add datetime 1970-01-01 00:00:00 to book messages.
=> Fix issue 295 patch.

common/c_cpp/src/c/strutils.c
Potential buffer overflow in strToVersionInfo. Detected using clang with
address sanitizer. No longer visible after fix. Common unit tests pass
as expected.
Signed-off By: Damian Maguire <dmaguire@velatt.com>
Address sanitizer reported issue when running `UnitTestCommonC`. Resolved after implementation of fix.
=> [COMMON] Fix potential buffer overflow in strToVersionInfo

mama/c_cpp/src/c/mama.c
Intended to resolve #145.
Adding support for automatic loading of payload bridges based on
properties defined in the mama.properties file. Payloads are loaded
during the call to mama_open, after the entitlements bridges and default
payload have been loaded, but before middleware bridges.
Payloads are loaded based on properties which match the following
pattern:
mama.payload.autload.<name>=True|False
Where 'name' is the same value expected in a call to
mama_loadPayloadBridge. Payload loading can then easily be disabled by
changing the value of the property to a 'false' value.
Tested with a range of valid and invalid payload bridges and properties.
Signed-off by: Damian Maguire <damian.j.maguire@gmail.com>
Add support for automatically loading payload bridges based on libraries defined in …
=> [MAMA] Add support for autoloading payload bridges from config.

common/c_cpp/src/c/properties.l, common/c_cpp/src/c/property.c, common/c_cpp/src/c/propertyinternal.h, common/c_cpp/src/c/strutils.c, common/c_cpp/src/c/wombat/strutils.h, common/c_cpp/src/gunittest/c/Makefile.sample, common/c_cpp/src/gunittest/c/SConscript, common/c_cpp/src/gunittest/c/strutilstest.cpp
This pull request will add support for extended environment variables
Signed-off-by: Gary Molloy <gmolloy@velatt.com>
Adds extended support for environment variables, including support for:
- both the $() and ${} notations
- multiple environment variables
A new unittest file has been added containing 9 tests
=> PLAT-1078: Extend support of environment variables

common/c_cpp/src/gunittest/c/UnitTestCommonC.vcxproj, common/c_cpp/src/gunittest/c/strutilstest.cpp
Recent environment variable support unit tests failed to build
on windows. This should allow it to build, and for the code to
be available in the corresponding Visual Studio project.
=> Fixed windows build issue for unit test

mama/c_cpp/src/c/plugin.c, mama/c_cpp/src/gunittest/c/openclosetest.cpp
Tracking variable of plugins "gPluginNo" is reset to 0 on shutdown of plugins.
This change resets the number of plugins back to 0, when shutting down plugins. This means that it is harder to reach the hardcoded limit of 100 Plugins by accident and removes certain program crashes and exceptions.
Added a unit test for this change, it opens and closes mama 150 times (well over the limit of 100). This unittest effectively tests that the number of plugins is reset on shutdown every time.
=> Reset number of plugins on shutdown

mama/c_cpp/src/c/bridge/qpid/endpointpool.c
thread-safe version of endpoint pool
Thread-safe version of endpoint pool -- see https://github.com/fquinner/OpenMAMA-zmq/issues/19
With this patch, the zmq transport no longer cores under load.
=> [MAMA] thread-safe version of endpoint pool

mama/c_cpp/src/c/plugin.c
loadPlugins can realloc to provide for more plugins
Changed max plugin limit to 20, when this is reached, the program now reallocs the memory assigned for it and doubles the amount of plugins it can store each time the limit is hit.
For testing, I changed the limit to be very low (2, then 1) and printed out when the memory was reallocated. I did this because I had 4 plugins with which I could test the change, and I could watch the limit be changed and the memory reallocated by using printf statements. However, since I dont have 20 plugins with which to test this change I cannot test this change with the current limit of 20 as it is. 
Signed-off-by: Aaron Sneddon <asneddon@velatt.com>
=> LoadPlugins Realloc

mama/c_cpp/src/c/queue.c
*This should be a brief one line description of the pull request*
There is a bug in the OpenMAMA and OpenMAMA-zmq code related to detaching messages that causes the payload to leak on every detach.  
When a message is detached, MAMA calls `mamaQueueImpl_detachMsg` which detaches the reusable message that is associated with the queue (by marking its mIsOwner flag), and then calls `mamaMsg_create` to create a new queue message.  
There are two problems with this code:
- `mamaMsg_create` also creates a payload, but that payload gets overwritten later on, and so the original payload leaks
- instead of calling `mamaMsg_create`, the detach code should probably be calling `mamaQueue_createReuseableMsg`, which is what is done to create the …
=> [MAMA] fix leak in mamaMsg_detach

mama/c_cpp/src/c/plugin.c
Double free was introduced by recent plugin change. This should
prevent it.
=> Reset plugins to null to avoid double free

mama/c_cpp/src/c/mama.c
Was previously in mama_close when it should have been in mama_stop
For details, see #319
=> MAMA: Moved background thread destroy to stop

mama/c_cpp/src/c/log.c
Has previously been WARN. It's unpleasant to have to set a log
level to WARN to print something by default. The onus should be
on the application to choose its default log level if NORMAL is
not efficient, but NORMAL should be the default. Otherwise
stats, versions etc have to declare themselves as warnings just
to get printed.
=> Modified MAMA default log level to NORMAL

mama/c_cpp/src/c/subscription.c
As reported in #300 - there was a copy and paste error
when the code was last refactored which is corrected with
this fix.
=> Fixed crash with entitlement subscription

mama/c_cpp/src/c/mama/queue.h, mama/c_cpp/src/cpp/mama/MamaQueue.h, mama/dotnet/src/cs/MamaQueue.cs
The behaviour of queue's timedDispatch method varies
depending on middleware, so updating the function's
API documentation across languages to reflect this.
=> Updated documentation for timedDispatch (#)

mama/c_cpp/src/c/mama.c, mama/c_cpp/src/cpp/mamacpp.cpp, mama/jni/src/c/mamajni.c, mama/jni/src/c/mamamsgjni.c, mama/jni/src/c/mamapayloadbridgejni.c
Fixed two JVM crash scenarios when calling Mama.loadPayloadBridge of Java API
Create a very simple dynamic library and compile:
foo.c:
```c
int f() {
return 1;
}
```
```shell
gcc -shared -o libmamafooimpl.so foo.c
```
This simple Java example will crash JVM:
```java
import com.wombat.mama.Mama;
public class Test {
public static void main(String[] args) {
Mama.loadPayloadBridge("foo");     // Test case 1 - Crash
Mama.loadPayloadBridge("qpidmsg"); // Test vase 2 - Crash
}
}
```
There are two crash scenarios:
1. Loading any (not MAMA bridge) dynamic library - crash because mama_loadPayloadBridge returns MAMA_STATUS_OK even if it can't find init function.
2. Loading MAMA payload bridge library - because of incorrect field name in …
=> Fixed few JVM crashes when calling Mama.loadPayloadBridge of Java API

common/c_cpp/src/c/SConscript, common/c_cpp/src/c/darwin/clock.c, common/c_cpp/src/c/darwin/port.c, common/c_cpp/src/c/darwin/port.h, common/c_cpp/src/c/linux/wUuid.h, site_scons/community/command_line.py
Adding a couple of changes to support building common and MAMA on OSX. 
Couple of fixes:
- Adding target_arch support to scons for Darwin
- Disable 'clock_gettime' implementation is OSX 12+
- Later OSX version have their own support for this, so adding version check to see if it's required.
- Implement cpu affinity support.
- OSX doesn't have an API that actually supports binding to specific cores, so implementing most of this as a no-op.
- Fix a new compiler error with uuid_clear
Build complete now as expected, unit tests are running fine.
=> OSX - Recent Updates

common/c_cpp/SConscript.win, common/c_cpp/src/c/SConscript.win, site_scons/community/command_line.py, site_scons/community/windows.py
This is a nice thing to have generally with flex on windows which
has multiple standard implementations, but it's specifically
useful for vcpkg which provides win_flex.exe as the binary name.
=> Added lex option to allow optional tool path

mamda/c_cpp/src/cpp/MamdaTradeListener.cpp
Removing a few duplicate fields which were created in commit 4cd88bbf.
Nothing really to it - clang complains. 
Build complete now as expected, unit tests are running fine.
=> MAMDA - Remove Duplicate Fields in Trade Listener

mama/c_cpp/src/c/SConscript, mama/c_cpp/src/c/SConscript.win, mama/c_cpp/src/c/bridge/qpid/SConscript, mama/c_cpp/src/c/bridge/qpid/SConscript.win, mama/c_cpp/src/c/payload/qpidmsg/SConscript.win, site_scons/community/command_line.py
Adding runtime libraries to the install package was causing
problems with packaging for shared deployment environments, so
making the behaviour configurable.
=> Added new option for disabling runtime install

mama/c_cpp/src/c/SConscript.win, mama/c_cpp/src/c/bridge/qpid/SConscript.win, site_scons/community/command_line.py, site_scons/community/windows.py
This option is a boolean which, if enabled, will expect windows
dependencies in the format produced by vcpkg.
=> Added vcpkg_build option for use with vcpkg

mama/c_cpp/src/c/msg.c, mama/c_cpp/src/gunittest/cpp/MamaMsgTest.cpp, release_scripts/ci-run.py, release_scripts/intentionalunittestleaks.supp
Added defensive code to mamaMsg_destroy so that it will not attempt
to destroy the underlying payload if the bridge has already been
unloaded. Includes unit test that crashed before fix was applied.
=> MAMA: Added defensive code to mamaMsg_destroy (#264)

mama/c_cpp/src/c/datetime.c
Timezone offset added to tv_usec instead of tv_sec.
- [ x] MAMAC
mamaDateTime_getStructTimeValWithTz() returns a struct timeval, with timezone offset applied.  The timezone is in seconds, not microseconds, so it should be added to tv_sec.
=> Mama date time get struct time val with tz fix

common/c_cpp/src/c/SConscript
Signed-off-by: Chris Morgan <Christopher.Morgan@solacesystems.com>
*Patch to common c SConscript to include header files*
*See Issue #371 *
=> Fix forcommon include files no longer being generated correctly from scons

mama/c_cpp/src/c/mama/subscription.h, mama/c_cpp/src/c/subscription.c
Signed-off-by: Chris Morgan <Christopher.Morgan@solacesystems.com>
*Restores `mamaSubscription_setRecoverGaps` and `mamaSubscription_getRecoverGaps` functions using the new DqStrategy functions*
*This PR fixes the issue #370. The functions, `mamaSubscription_setRecoverGaps` and `mamaSubscription_getRecoverGaps` were removed in the latest release of OpenMAMA version 6.2.2. They seemed to be replaced by internal only functions `Dqstrategy_setRecoverGaps` and `Dqstrategy_getRecoverGaps` as a part of commit 1160121444b0fa5a8df6ebbe048583c7466a4b66.*
*Built the solace bridge which is dependent on the missing functions on the following platforms, linux: x86_64, i386; windows: Win32 and Win64. Ran Openmama bridge integration tests and solace …
=> Restore mamaSubscription RecoverGaps functions

mamda/c_cpp/src/cpp/orderbooks/MamdaBookAtomicListener.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBook.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookBasicDelta.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookBasicDeltaList.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookConcreteComplexDelta.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookEntry.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookFields.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookListener.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookPriceLevel.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookWriter.cpp, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaBookAtomicLevelEntry.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaBookAtomicListener.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBook.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBookBasicDelta.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBookBasicDeltaList.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBookEntry.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBookFields.h, mamda/c_cpp/src/cpp/orderbooks/mamda/MamdaOrderBookPriceLevel.h, mamda/c_cpp/src/examples/orderbooks/atomicbookbuilder.cpp, mamda/c_cpp/src/examples/orderbooks/atomicbookticker.cpp, mamda/c_cpp/src/examples/orderbooks/bookticker.cpp, mamda/java/src/main/java/com/wombat/mamda/examples/MamdaBookTicker.java, mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookEntry.java, mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookFields.java, mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookListener.java, mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookPriceLevel.java, mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookWriter.java
This change allows us to set the entry position inside a price level for an entry. This is achieved using wEntryPosition field.
these changes allow entries in a book to be stored in an order based on the value of the wEntryPosition field received in incoming messages.  If no wEntryPosition is received the orders will be stored as they normally are.  Added functions to retrieve entry position from entries.
Tested these changes by using an order injector connected to a publisher which supports publishing of entry positions.
=> ENTRY POSITION SUPPORT

mama/c_cpp/src/examples/c/mamapublisherc.c
*The example mamapublisherc cores during shutdown from not destroy the timer when finished publishing.*
The example application mamapublisherc cores when when given the argument `-c <n>` to exit after n messages published. Based on the back trace:
```
(gdb) bt
#0  0x00007f6ba949f0e0 in ?? ()
#1  0x00007f6bab81195f in mamaMsg_clear () from /home/cmorgan/cvs/gitProjects/openmama/fork/build/mama/c_cpp/src/c/libmama.so
#2  0x0000000000401b9a in publishMessage ()
#3  0x00000000004020a0 in timerCallback ()
#4  0x00007f6bab35b6e9 in wombatQueue_dispatchInt ()
from /home/cmorgan/cvs/gitProjects/openmama/fork/build/common/c_cpp/src/c/libwombatcommon.so
#5  0x00007f6bab35b76a in wombatQueue_timedDispatch ()
from …
```
=> Fix for mamapublisherc core on exit

mama/c_cpp/src/cpp/mama/fieldcache/MamaFieldCache.h
Updated the headers for the find() functions to more accurately reflect what
happens in the function.
N/A
=> PLAT-1453: MamaFieldCache::find( ) header update

mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookListener.cpp
The issue was that the source was not an optimised feed and therefore we were not receiving the required fields required to reset certain orderbook fields that we default (in particular `mBookMsgFields.mNumLevels`)
The solution was to add a check for a blank initial.
Using a simple bookticker that is outputting `book.getNumBidLevels()` and `book.getNumAskLevels()` and subscribing to a non-existent book shows the issue:
Before:
```
RECAP!!!  (seq# 0)
Book for: bGARY.NYS
BID:
Levels - 1       <<<<<<<<<<<<<<<
ASK:
Levels - 0
Time     Num    Size   Price Act | Act Price   Size    Num       Time
```
After:
```
RECAP!!!  (seq# 0)
Book for: bGARY.NYS
BID:
Levels - 0
ASK:
Levels - 0
Time     Num    Size   Price Act | Act Price   Size    Num       Time
```
=> PLAT-1449: Mamda app includes phantom bid

mama/c_cpp/src/c/playback/playbackcapture.c
If we try to create a playback, on Windows, using the `capturec` example application everything seems fine, but then trying to replay the file with `capturereplayc` fails with the error:
```2018-05-17 15:22:40: wmsgPayload_setByteBuffer(): wombatmsg_setNewBuffer() Failed. [3]```
The solution is to open the file for capture with the binary flag which is compatible with both Windows and Linux.
Replaying the playback works as expected (on both Windows and Linux).
=> Windows Capture Corrupt

common/c_cpp/src/c/linux/machine.c, mama/c_cpp/src/c/conflation/connection.c, mama/c_cpp/src/c/conflation/connection_int.h, mama/c_cpp/src/c/playback/playbackpublisher.c, mama/c_cpp/src/c/transport.c, mama/c_cpp/src/examples/cpp/mamalistencachedcpp.cpp, mama/c_cpp/src/examples/cpp/mamalistencpp.cpp, mamda/c_cpp/src/cpp/MamdaQuoteListener.cpp, mamda/c_cpp/src/cpp/MamdaSubscription.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaBookAtomicListener.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBook.cpp, mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookEntry.cpp
Mostly in the MAMDA area. While I was there I also fixed some warnings
introduced by newer versions of gcc around string buffer length checks
to prevent overflows.
=> Fixed warnings coming up from recent contributions

mama/c_cpp/src/c/msg.c
Dictionary was not being passed to recursive calls to parse MAMA
messages as json, so submsgs and vectors of messages were not having
their field names rendered correctly before this fix.
=> Fixed issue with field names in sub msg

mamda/c_cpp/src/cpp/orderbooks/MamdaOrderBookListener.cpp
MamdaOrderBookListener entry based deletes incorrectly add to bid/ask side maps
When the feedhandler is wirecache and the orderbooks are entry based, deletes were incorrectly
being added to the Ask/Bid side maps causing the functions getNumBidLevels() and
getNumAskLevels() to return incorrect values.
You can easily see this happen if you miss some price levels at the start and then later receive an entry delete for a non-existent price level.
To test, modify a bookticker.cpp and put the following into the top of the prettyPrint() function:
```
cout << "Book for: " << symbol << endl;
cout << "BID:" << endl;
cout << "    Levels - " << book.getNumBidLevels() << endl;
cout << "ASK:"<< endl;
cout << "    Levels - " << book.getNumAskLevels() << endl;
```
Subscribing to a V5 entry based …
=> MamdaOrderBookListener entry based deletes incorrectly add to bid/ask side maps

mama/c_cpp/src/c/listenermsgcallback.c
Signed-off-by: Aaron Sneddon <asneddon@velatt.com>
This change restores a conditional that was removed with the dqstrategyplugin change. The conditional was removed from  listenermsgcallback.c and without it, a crash was experienced with multiple initial snapshots for a group subscription, and dqstrategy disabled.
The dqstrategyplugin change removed a conditional from line 158 in listenermsgcallback.c. The functionality containing this line was moved to dqstrategyplugin.c and down in listenermsgcallback.c into processMsg. The problem is: when the functionality was added to dqstrategyplugin, the conditional guarding stopWaitForResponse was kept, but in processMsg that function call was unguarded with dqstrategy disabled.
This lead to a …
=> Restored conditional in listenermsgcallback.c

common/c_cpp/src/c/thread.c, mama/c_cpp/src/c/mama.c
De-allocate memory used by wtables when mama_close is called
- [ X] MAMAC
Memory allocated by wtables is currently not released when mama_close is called and it shows as memory leak when profiling an OpenMAMA client app.  This change will release the memory.
=> Wtable destroy

mama/c_cpp/src/c/dqstrategyplugin/dqstrategyplugin.c, mama/c_cpp/src/c/mama.c, mama/c_cpp/src/c/plugin.c
Fixed issue whereby calling mama_open() and mama_close() several times could result in a core on a subsequent close.
Destroys tables on shutdown and decrements variable so that they are repopulated on mama_open(), also includes guarding and freeing of pluginInfo
Tested this with an application which allows mama_open() and mama_close() to be called several times in any order
Signed-off-by: Aaron Sneddon <asneddon@velatt.com>
=> multiple_open_close

README.md, docker/Dockerfile, docker/README.md, docker/docker-entrypoint.sh, docker/mama.docker.properties, docker/profile.openmama.sh
This is the code used to produce openmama/openmama on dockerhub. This
allows users to provide applications using only their binary and run
demo apps with and easily swap out components for different
configuration / middlewares etc.
=> Added docker integration scripts and configs for qpid

common/c_cpp/src/c/CMakeLists.txt
Signed-off-by: Chris Morgan <Christopher.Morgan@solacesystems.com>
This is an attempt to fix issue #398 
The cmake list will now install the windows platform header files.
=> Include system platform headers on windows

mama/c_cpp/src/c/msg.c, mama/c_cpp/src/c/payload/qpidmsg/payload.c, mama/c_cpp/src/c/payload/qpidmsg/qpidpayloadfunctions.h, mama/c_cpp/src/c/payloadbridge.h, mama/c_cpp/src/gunittest/c/mamamsg/msggeneraltests.cpp, mama/c_cpp/src/gunittest/c/payload/fieldcompositetests.cpp, mama/c_cpp/src/gunittest/c/payload/payloadcompositetests.cpp, mama/c_cpp/src/gunittest/c/payload/payloadgeneraltests.cpp
Updated payload bridge function definitions to pass mamaMsg types to payload bridges instead of msgPayload.
Issue #297 found that the payload bridge functions where inconsistent passing mamaMsg for the msg modifiers, mamaMsg_addMsg and mamaMsg_updateSubMsg, where mamaMsg_addMsg would pass a msgPayload and mamaMsg_updateSubMsg a mamaMsg for the value. #297 determined that mamaMsg should be pass to the payload bridge instead of msgPayload to allow a payload bridge to transcode messages from different bridges. This pull request should update the two payload bridge function definitions msgPayload_addMsg and msgPayload_updateSubMsg and all references to them in the tests and the smaple bridge qpid.
The updated tests should pass.
I verified the …
=> Update Payload Bridge functions for transcode message support

mama/c_cpp/src/c/publisher.c
Moved the mamaTransport_removePublisher call outside of the publisher's
create / destroy lock since it is an operation of context sensitivity
which is already managed exclusively by the MAMA transport object.
=> [#411] MAMA Subscription / Transport teardown deadlock

mama/c_cpp/src/c/mama/integration/subscription.h, mama/c_cpp/src/c/subscription.c, mama/jni/src/c/mamasubscriptionjni.c, mama/jni/src/main/java/com/wombat/mama/examples/MamaListen.java
In some scenarios, it may be possible for a garbage collector and a
bridge thread to attempt to deallocate or access deallocated memory
at the same time. This should prevent this from happening by only
permitting a deallocation when the final reference has registered
disinterest in the subscription.
=> Updated subscriptions to use reference count for GC

common/c_cpp/src/c/timers.c, common/c_cpp/src/c/timers.h
- need to synchronize timer create/destroy -- see https://github.com/nyfix/OZ:
- fix race condition between timer destroy and reset - expose lock/unlock on timer heap (needed to avoid deadlock)	74e7803	wtorpey <bill.torpey@ullink.com>	Dec 12, 2017 at 10:35 AM
=> need to synchronize timer create/destroy 

mama/c_cpp/src/c/mama.c, mama/c_cpp/src/c/mamainternal.h, mama/c_cpp/src/c/msg.c, mama/c_cpp/src/c/payloadbridge.h
- helps w/RAII-style designs where mamaMsgs may be used outside the bounds of mama_open/mama_close
=> provide option to keep payload library loaded even after mama_close

.github/workflows/main.yml
Cloudsmith does not yet have centos stream separated from el/8.
=> Disable centos stream upload for cloudsmith

mama/c_cpp/src/gunittest/c/iotest.cpp
- properly handle situation where MamaIO is not implemented (see https://github.com/finos/OpenMAMA/issues/458)
=> - properly handle situation where MamaIO is not implemented

mama/c_cpp/src/c/datetime.c
AddressSanitizer detects a buffer overrun in date/time tests.
```
=================================================================
==878864==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ec72 at pc 0x0000004c3414 bp 0x7ffc26f6c250 sp 0x7ffc26f6ba10
READ of size 3 at 0x60200000ec72 thread T0
#0 0x4c3413 in strchr (/home/btorpey/install/OpenMAMA/master/asan/bin/UnitTestMamaDateTimeC+0x4c3413)
#1 0x7fbde16d1c36 in mamaDateTime_setFromStringWithTz /home/btorpey/work/OpenMAMA/master/src/mama/c_cpp/src/c/datetime.c:375:31
#2 0x7fbde16d24af in mamaDateTime_setFromStringBufferWithTz /home/btorpey/work/OpenMAMA/master/src/mama/c_cpp/src/c/datetime.c:491:14
#3 0x7fbde16d24af in mamaDateTime_setFromStringBuffer …
```
=> - fix buffer overrun

CMakeLists.txt, mama/CMakeLists.txt, mama/c_cpp/src/c/bridge/noop/transport.c, mama/c_cpp/src/c/bridge/ompb/CMakeLists.txt, mama/c_cpp/src/c/bridge/ompb/bridge.c, mama/c_cpp/src/c/bridge/ompb/bridgefunctions.h, mama/c_cpp/src/c/bridge/ompb/publisher.c, mama/c_cpp/src/c/bridge/ompb/subscription.c, mama/c_cpp/src/c/bridge/ompb/transport.c, mama/c_cpp/src/c/bridge/ompb/transport.h, mama/c_cpp/src/examples/mama.properties
This bridge will help allow users to test their applications without having
to set up an out-of-process publisher to connect to. It can be built by adding
the following option to cmake:
-DWITH_OMPB_BRIDGE=ON
And can then be used with `-m ompb` where the following mama.properties config
parameters are supported (given a transport name of 'pb'):
mama.ompb.transport.pb.file = /path/to/playback.mplay
mama.ompb.transport.pb.rate = 100000
mama.ompb.transport.pb.on_completion = rewind
Note that you can also pass "raise" to the on_completion parameter to get the
bridge to raise a SIGINT on playback completion which can then be caught in
your application to clean up the test run.
=> Added new OpenMAMA Playback Bridge (ompb)

mama/jni/src/c/mamamsgfieldjni.c
Calling getMsg causes a bug when finalizer kicks in since it tries
to clean up memory which it does not own. This implementation makes
getMsg operate on a copy to correct this behaviour.
=> Bugfix for Java MamaMsgField.getMsg crash

mama/jni/src/c/mamamsgjni.c, mama/jni/src/c/mamapricejni.c, mama/jni/src/main/java/com/wombat/mama/MamaMsg.java
The createFromByteBuffer implementation never really looks like it worked
property because it reused the same underlying c static buffer for all
calls to it, and it could not be re-used. This version will handle the
operation property by allowing the Java object to track the associated
memory.
=> Bugfix for Java MamaMsg.createFromByteBuffer and setNewBuffer

mama/c_cpp/src/c/mama.c, mama/c_cpp/src/c/mama/mama.h, mama/c_cpp/src/cpp/mama/mamacpp.h, mama/c_cpp/src/cpp/mamacpp.cpp, mama/dotnet/src/cs/ISourceManager.cs, mama/dotnet/src/cs/MAMA.cs, mama/dotnet/src/cs/MamaBasicSubscription.cs, mama/jni/src/c/mamajni.c, mama/jni/src/main/java/com/wombat/mama/Mama.java, mamda/java/src/main/java/com/wombat/mamda/orderbook/MamdaOrderBookPriceLevel.java
This will start / stop all currently loaded middleware bridges rather than
needing to track MAMA bridge handles within the user's application.
=> Added mama.startAll and mama.stopAll for C, C++, C# and Java

mama/c_cpp/src/c/mama.c, mama/c_cpp/src/c/mama/mama.h, mama/c_cpp/src/cpp/mama/mamacpp.h, mama/c_cpp/src/cpp/mamacpp.cpp, mama/c_cpp/src/gunittest/c/CMakeLists.txt, mama/c_cpp/src/gunittest/c/mamainternaltest.cpp, mama/dotnet/src/cs/MAMA.cs, mama/jni/src/c/mamajni.c, mama/jni/src/main/java/com/wombat/mama/Mama.java
This is to make it easier to find properties matching patterns,
particularly in higher level languages which had no existing option
for doing this.
The mama_getAvailableTransportNames implementation is purely based
on the properties available in currently loaded configuration.
This change includes mama_getPropertiesAsString which will list
all properties in a single allocated string buffer for easy parsing
in higher level languages.
=> Added mama_getAllProperties and mama_getAvailableTransportNames

mama/c_cpp/src/c/subscription.c, mama/c_cpp/src/cpp/MamaBasicSubscription.cpp, mama/c_cpp/src/cpp/mama/MamaBasicSubscription.h, mama/c_cpp/src/cpp/mama/MamaBasicSubscriptionCallback.h, mama/c_cpp/src/cpp/mama/MamaBasicWildCardSubscriptionCallback.h, mama/c_cpp/src/cpp/mama/MamaSubscriptionCallback.h
Added default implementations for gap, recap etc which will log
when they are received and high level details.
Also added subscription wrapper for MamaBasicSubscription in C++
which will allow the caller to use standard MamaSubscriptionCallback
rather than having to use separate basic subscription callbacks.
Also onCreate, onQuality and onError is no longer mandatory for
MAMA C++.
=> Added default MAMA subscription callbacks and Basic Wrapper

mama/c_cpp/src/cpp/MamaQueueGroup.cpp, mama/c_cpp/src/cpp/MamaSubscription.cpp, mama/c_cpp/src/cpp/mama/MamaQueueGroup.h, mama/dotnet/src/cs/MamaQueueGroup.cs, mama/jni/src/main/java/com/wombat/mama/MamaQueueGroup.java, mama/jni/src/main/java/com/wombat/mama/MamaSubscription.java
This will return a specific queue group within the group based
on a numerical index.
Also added MamaSubscription.getQueue for Java since it was missing.
=> Added MamaQueueGroup.getQueueGroupByIndex for C++, C# and Java

mama/c_cpp/src/c/transport.c
There appears to be a Heisenbug lurking in Mama that can cause intermittent failure in the unit tests (specifically `MamaSubscriptionTest.SubscriptionCreateDestroy` in `UnitTestMamaC`) and by extension in any code using subscriptions (which is pretty much all Mama applications).  The bug causes `mamaSubscription_create` to fail with the error "mamaSubscription_setupBasic(): Could not find entitlement bridge!".
So far I've only seen this in one specific environment: CentOS 7 with clang 10.0.1 and Address Sanitizer.  The same test runs fine with clang without ASAN, with gcc, and with all the above on Ubuntu 20.04.
Here's the bug (from `src/mama/c_cpp/src/c/transport.c:940`):
``` 
if (strlen((char*)gEntitlementBridges))   /* If entitlement bridges were built in at compile time. */
```
The …
=> fix for bad cast

CMakeLists.txt, cmake/OpenMAMAConfig.cmake.in, common/c_cpp/src/c/CMakeLists.txt, devops/build/ci-run.sh, devops/build/install-dependencies.sh, tutorials/c/01-quickstart/CMakeLists.txt, tutorials/c/01-quickstart/quickstart.c, tutorials/c/02-resourcepool/CMakeLists.txt, tutorials/c/02-resourcepool/resourcepool.c, tutorials/cpp/01-quickstart/CMakeLists.txt, tutorials/cpp/01-quickstart/quickstart.cpp, tutorials/cpp/02-resourcepool/CMakeLists.txt, tutorials/cpp/02-resourcepool/resourcepool.cpp
These changes include:
- Added OpenMAMA Config and target options for modern Cmake use
(this should now make OpenMAMA work with vanilla find_package)
- Cmake minimum version required is now 3.16
- Updated tutorials to not use getopt to work natively on windows
- Fixed windows issue with some headers being missing from install
- Fixed Ubuntu 18 build to use more recent ruby so FPM would work
- Added aprutil to dependencies for vcpkg and apt / yum
=> Several fixes to improve packaging and experience

CMakeLists.txt
It would have worked before anyway, but this adds some help documentation and improves how it is detected.
=> Added BIN_GRADLE configuration option

mama/c_cpp/src/c/transport.c
Previously the only option was to set a global parameter:
mama.throttle.interval = 1000
Now we have an additional transport-specific option:
mama.transport.<transport name>.throttle.interval = 1000
=> Added new MAMA property for subscription throttling on a transport
